include_recipe "sprout-osx-apps::chrome"
include_recipe "sprout-osx-apps::chrome_canary"
include_recipe "sprout-osx-apps::firefox"
include_recipe "sprout-osx-apps::firefox_aurora"
include_recipe "sprout-osx-apps::freeruler"
include_recipe "sprout-osx-apps::jpegoptim"
include_recipe "sprout-osx-apps::optipng"
include_recipe "sprout-osx-apps::node_js"
include_recipe "sprout-osx-apps::phantomjs"
include_recipe "sprout-osx-apps::selenium_webdriver"

